HOMEDIR = './'
MASTER_CLIENT_ADDR = ('localhost', 9080) # client side server on master node
MASTER_NODE_ADDR = ('localhost', 9090)   # file node facing server on master node
FILE_NODE_ADDR = ('localhost', 9101)     # server running on file node
DEFAULT_MASTERNODE_REGISTRY_FILENAME = './registrydata/reg.data'
PICKLE_PROTOCOL = 1
BUFSIZE = 1024
N_COPIES = 30
NODES_PER_FILE = 3 #k
WAIT_INTERVAL = 0.1 # 100ms --
